CREATE TABLE [dbo].[TBLLOGIN] (
    [EMAIL]     VARCHAR (50) NOT NULL,
    [KULLANICI] VARCHAR (50) NULL,
    [SIFRE]     INT NULL,
    CONSTRAINT [PK_TBLLOGIN] PRIMARY KEY CLUSTERED ([EMAIL] ASC)
);

